// <auto-generated />
using System;
using Labb3_Rasmus_AnropaDB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Labb3_Rasmus_AnropaDB.Migrations
{
    [DbContext(typeof(Labb3DBContext))]
    [Migration("20240124125715_En person tillagd i personal")]
    partial class Enpersontillagdipersonal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Labb3_Rasmus_AnropaDB.Models.TblBetyg", b =>
                {
                    b.Property<string>("Betyg")
                        .HasMaxLength(1)
                        .IsUnicode(false)
                        .HasColumnType("varchar(1)");

                    b.Property<DateOnly?>("Betygsdatum")
                        .HasColumnType("date");

                    b.Property<int?>("KursId")
                        .HasColumnType("int")
                        .HasColumnName("KursID");

                    b.Property<int?>("PersonalId")
                        .HasColumnType("int")
                        .HasColumnName("PersonalID");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    b.HasIndex("KursId");

                    b.HasIndex("PersonalId");

                    b.HasIndex("StudentId");

                    b.ToTable("tblBetyg", (string)null);
                });

            modelBuilder.Entity("Labb3_Rasmus_AnropaDB.Models.TblKur", b =>
                {
                    b.Property<int>("KursId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("KursID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KursId"));

                    b.Property<string>("KursNamn")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("KursId")
                        .HasName("PK__tblKurs__BCCFFF3B9915B108");

                    b.ToTable("tblKurs", (string)null);
                });

            modelBuilder.Entity("Labb3_Rasmus_AnropaDB.Models.TblPersonal", b =>
                {
                    b.Property<int>("PersonalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PersonalID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonalId"));

                    b.Property<string>("Befattning")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("PersonalId")
                        .HasName("PK__tblPerso__28343713D1BDB47D");

                    b.ToTable("tblPersonal", (string)null);
                });

            modelBuilder.Entity("Labb3_Rasmus_AnropaDB.Models.TblStudent", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("StudentID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("FirstName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Klass")
                        .HasMaxLength(25)
                        .IsUnicode(false)
                        .HasColumnType("varchar(25)");

                    b.Property<string>("LastName")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Personnr")
                        .HasMaxLength(13)
                        .HasColumnType("nchar(13)")
                        .IsFixedLength();

                    b.HasKey("StudentId")
                        .HasName("PK__tblStude__32C52A793A19FAEC");

                    b.ToTable("tblStudent", (string)null);
                });

            modelBuilder.Entity("Labb3_Rasmus_AnropaDB.Models.TblBetyg", b =>
                {
                    b.HasOne("Labb3_Rasmus_AnropaDB.Models.TblKur", "Kurs")
                        .WithMany()
                        .HasForeignKey("KursId")
                        .HasConstraintName("tblBetyg_KursID_FK");

                    b.HasOne("Labb3_Rasmus_AnropaDB.Models.TblPersonal", "Personal")
                        .WithMany()
                        .HasForeignKey("PersonalId")
                        .HasConstraintName("tblBetyg_PersonalID_FK");

                    b.HasOne("Labb3_Rasmus_AnropaDB.Models.TblStudent", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .HasConstraintName("tblBetyg_StudentID_FK");

                    b.Navigation("Kurs");

                    b.Navigation("Personal");

                    b.Navigation("Student");
                });
#pragma warning restore 612, 618
        }
    }
}
